// * Application
export const SET_CURRENT_JOBS = "SET_CURRENT_JOBS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_FULL_TIME = "SET_FULL_TIME";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_JOBS = "SET_JOBS";
export const SET_JOBS_FETCHED_AT = "SET_JOBS_FETCHED_AT";
export const SET_LOCATION_SEARCH = "SET_LOCATION_SEARCH";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";

// * User
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const SET_EDIT_EMAIL = "SET_EDIT_EMAIL";
export const SET_EDIT_NAME = "SET_EDIT_NAME";
export const SET_EMAIL = "SET_EMAIL";
export const SET_FORM_ERROR = "SET_FORM_ERROR";
export const SET_IS_EDITING_PROFILE = "SET_IS_EDITING_PROFILE";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const SET_IS_RESETTING_PASSWORD = "SET_IS_RESETTING_PASSWORD";
export const SET_NAME = "SET_NAME";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_RESET_CONFIRM_NEW_PASSWORD = "SET_RESET_CONFIRM_NEW_PASSWORD";
export const SET_RESET_CURRENT_PASSWORD = "SET_RESET_CURRENT_PASSWORD";
export const SET_RESET_NEW_PASSWORD = "SET_RESET_NEW_PASSWORD";
