export const SET_CURRENT_JOBS = "SET_CURRENT_JOBS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_FULL_TIME = "SET_FULL_TIME";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_JOBS = "SET_JOBS";
export const SET_JOBS_FETCHED_AT = "SET_JOBS_FETCHED_AT";
export const SET_LOCATION_SEARCH = "SET_LOCATION_SEARCH";
