// * Application
export const DISPLAY_NOTIFICATION = "DISPLAY_NOTIFICATION";
export const SET_CURRENT_JOBS = "SET_CURRENT_JOBS";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_ERROR = "SET_ERROR";
export const SET_FULL_TIME = "SET_FULL_TIME";
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_JOB_DETAILS = "SET_JOB_DETAILS";
export const SET_JOBS = "SET_JOBS";
export const SET_LOCATION_SEARCH = "SET_LOCATION_SEARCH";
export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";

// * Modal
export const SET_IS_MODAL_OPEN = "SET_IS_MODAL_OPEN";
export const SET_MODAL_CONTENT = "SET_MODAL_CONTENT";
export const SET_MODAL_TITLE = "SET_MODAL_TITLE";

// * User
export const SET_CONFIRM_PASSWORD = "SET_CONFIRM_PASSWORD";
export const SET_EDIT_EMAIL = "SET_EDIT_EMAIL";
export const SET_EDIT_NAME = "SET_EDIT_NAME";
export const SET_EMAIL = "SET_EMAIL";
export const SET_HIDDEN_JOBS = "SET_HIDDEN_JOBS";
export const SET_HIDDEN_JOBS_DETAILS = "SET_HIDDEN_JOBS_DETAILS";
export const SET_IS_EDITING_PROFILE = "SET_IS_EDITING_PROFILE";
export const SET_IS_LOGGED_IN = "SET_IS_LOGGED_IN";
export const SET_NAME = "SET_NAME";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_RESET_CONFIRM_NEW_PASSWORD = "SET_RESET_CONFIRM_NEW_PASSWORD";
export const SET_RESET_CURRENT_PASSWORD = "SET_RESET_CURRENT_PASSWORD";
export const SET_RESET_NEW_PASSWORD = "SET_RESET_NEW_PASSWORD";
export const SET_SAVED_JOBS = "SET_SAVED_JOBS";
export const SET_SAVED_JOBS_CURRENT_PAGE = "SET_SAVED_JOBS_CURRENT_PAGE";
export const SET_SAVED_JOBS_DETAILS = "SET_SAVED_JOBS_DETAILS";
export const SET_SAVED_JOBS_TOTAL_PAGES = "SET_SAVED_JOBS_TOTAL_PAGES";
